x86/tools: Scope uapi include dirs to vdso2c
With a76108d05ee1 ("x86/entry/vdso: Move vdso2c to arch/x86/tools"),
-I$(srctree)/include/uapi and -I$(srctree)/arch/$(SUBARCH)/include/uapi
were added to HOST_EXTRACFLAGS, which also applies to hostprogs like tools/insn_sanity.

As a result <asm/insn.h> -> <asm/byteorder.h> -> <linux/swab.h> now
resolves to include/uapi/linux/swab.h when building insn_sanity. However the
uapi header uses __attribute_const__ which is normally undefined.

	In file included from /home/achill/git/linux/include/uapi/linux/byteorder/little_endian.h:14,
	                 from /usr/include/asm/byteorder.h:5,
	                 from /home/achill/git/linux/tools/arch/x86/include/asm/insn.h:10,
	                 from /home/achill/git/linux/arch/x86/tools/insn_sanity.c:17:
	/home/achill/git/linux/include/uapi/linux/swab.h:48:15: error: unknown type name '__attribute_const__'; did you mean '__attribute__'?
	   48 | static inline __attribute_const__ __u16 __fswab16(__u16 val)
	      |               ^~~~~~~~~~~~~~~~~~~
	      |               __attribute__

So only include the uapi include dirs when building vdso2c.

Fixes: a76108d05ee1 ("x86/entry/vdso: Move vdso2c to arch/x86/tools")
Cc: stable@vger.kernel.org
Signed-off-by: Achill Gilgenast <achill@achill.org>